# Generated by Django 6.0.2 on 2026-03-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Archived', 'Archived')], db_index=True, default='Pending', max_length=20),
        ),
    ]
